name: selfbot

on:
  workflow_dispatch:

concurrency:
  group: selfbot
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 330
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Instala deps
        run: |
          pip install --quiet -r requirements.txt
      - name: Roda selfbot
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          ALT_TOKEN: ${{ secrets.ALT_TOKEN }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        run: python -u selfbot.py